### ISSUE TITLE
how to ues labelFormat or other configuration to design bar label ？and how to change ranklabel configuration？

### ISSUE THREAD

**Issue by AdamYLK** [Jannchie/anichart.js#108]
## i want to hidden the right label which out of bar but to show the left label which in bar。
![the green rect show two label i want change](https://user-images.githubusercontent.com/13025698/168930610-654bec33-f7d6-4bc8-911d-0d1ceb45bcb0.png)
(the green rect show two labels which i want change)
how ever, i use labelFormat function to return empty string
![image](https://user-images.githubusercontent.com/13025698/168930864-8c5b7298-961d-4e6a-abea-06e4276fcbd2.png)
next the vision show that two of label all hidden...
![image](https://user-images.githubusercontent.com/13025698/168930059-98d88ca4-2d92-4402-b1c2-07ece3e8b750.png)
i want know how to made it，thx !

and second question, how to change ranklabel configuration？
![image](https://user-images.githubusercontent.com/13025698/168931276-93300445-e837-4346-8969-de9ddcf348fd.png)
(the green rect show the ranklabel)
i want to change font size and color to adapt background-image's color

best wish to you!

**Comment by Jannchie** [comment]
@AdamYLK  Thanks for using.

> next the vision show that two of label all hidden...

The label on bar is called "bar info". If you haven't set the `barInfoFormat`, it will use `labelFormat`.
So, you should set the `barInfoFormat`, like this:

```js
{
  barInfoFormat: (id) => id,
}
```

**Comment by Jannchie** [comment]
> i want to change font size and color to adapt background-image's color

Rank label font size is calculated by `barHeight` and `barFontSizeScale`. I think you should set `barFontSizeScale`.
It is really cannot modify the color at present, I will improve it in the future.

**Comment by Jannchie** [comment]
> THX a lot，it's my fault，pure english code make me confuse each configure's use

This is my problem. I should have provided the documentation.

**Comment by Jannchie** [comment]
Sorry for the wait, but I am working on a new version of the documentation and have completed the section on chart configuration items. The new documentation is now available at https://anichart.vercel.app/.
