### ISSUE TITLE
新手请教几个问题

### ISSUE THREAD

**Issue by bilirz** [Jannchie/anichart.js#117]
1.如何设置Barcharts数字后面的后缀呢，如您视频中的“xx/周”
2.如何设置Barcharts数字后缀后面的数字呢，如您视频中的“xx粉/每周  [xx万粉]”
3.如何显示Barcharts柱子上的文字前面的标签呢，如您视频中的“中国 - 张怡宁”
感谢见齐大大解答。

**Comment by Jannchie** [comment]
1,2. `valueFormat` 选项可以设置数字。
3. `barInfoFormat` 选项可以用来设置柱子上文字的标签。

这些 Format 选项接受一个函数，参数（应该有三个）是当前帧的数据，返回一个字符串。

**Comment by bilirz** [comment]
感谢见齐大大解答，我再试试。
