### ISSUE TITLE
请教一个关于BaseChart.interpolateInitValue的问题

### ISSUE THREAD

**Issue by bilirz** [Jannchie/anichart.js#118]
请教一个小问题：
我的数据是这样的

> id,value,date
a,1,2010
a,2,2011
b,2,2011
b,5,2012
c,4,2012

a没有2012年的数据，但是a仍然在柱状图上，数据保持在2，如果我不能设置a,0,2012，我该如何把a从柱状图上移除呢？
我尝试把BaseChart.interpolateInitValue设置成NaN或0但没有效果。
感谢见齐大大解答。

**Comment by Jannchie** [comment]
加一行
```
a,-,2012
```
试试

**Comment by bilirz** [comment]
好的好的，我去试试
