### ISSUE TITLE
[TODO] Video export

### ISSUE THREAD

**Issue by Jannchie** [Jannchie/anichart.js#12]
**Task name**
Video export
**Description of this task**
The refactored library does not yet have a live video export capability. It should be added as soon as possible.

**Comment by hepesu** [comment]
一个建议，感觉可以考虑用WebRTC做导出，这样用户可以不用FFMPEG，方便网页端。

https://github.com/muaz-khan/WebRTC-Experiment

**Comment by Jannchie** [comment]
> 一个建议，感觉可以考虑用WebRTC做导出，这样用户可以不用FFMPEG，方便网页端。
> 
> https://github.com/muaz-khan/WebRTC-Experiment

不太了解WebRTC，学习了

**Comment by Jannchie** [comment]
> 一个建议，感觉可以考虑用WebRTC做导出，这样用户可以不用FFMPEG，方便网页端。
> 
> https://github.com/muaz-khan/WebRTC-Experiment

试用了WebRTC，输出的质量似乎不太可控，我优化了FFmpeg的使用方式，现在支持多线程导出，效率够高了。
