### ISSUE TITLE
Feature request: 为条形图添加axis轴的绘制功能

### ISSUE THREAD

**Issue by bilirz** [Jannchie/anichart.js#120]
您好，我是anichart.js的长期使用者，我非常感谢您在这个框架上所做的工作，我一直从您的努力中受益良多。我有一个特性请求，希望您能考虑一下。
我想在柱状图中增加一个参数，用于**绘制axis轴**。用户可以**选择是否启用该轴**，这对于展示视频中的数据变化和增长非常有用。axis轴的值可以反映数据的变化，并且还可以帮助阐明条形图的区间范围。
我一直渴望这个功能的加入，我相信它会丰富anichart.js的功能，使其变得更加强大，希望您能考虑。
再次感谢您对anichart.js的付出和支持！

**Comment by Jannchie** [comment]
在最新的版本中，（v3.3.0）已经添加了。

**Comment by bilirz** [comment]
万分感谢您的付出！
