### ISSUE TITLE
Feature request: 请求增加柱状图柱子变换速率的参数

### ISSUE THREAD

**Issue by bilirz** [Jannchie/anichart.js#122]
有时候，当数据量很大时，使用remotion导出的速度会变得很慢。为了解决这个问题，我决定直接进行屏幕录制。然而，由于数据量太大，直接录制会导致掉帧的情况发生。为了解决这个问题，我考虑将录制的视频慢放10倍，然后在后期再加速10倍。然而，我发现anichart.js的变换速率[它的前身](https://github.com/Jannchie/Historical-ranking-data-visualization-based-on-d3.js)不同。不论速度设置为多少，anichart.js的柱子变换速率始终保持一致。因此，我希望能在柱状图中添加一个参数，用于控制柱子变换的速率，这样用户就可以根据需要自行选择。
非常感谢您的耐心阅读和考虑！

**Comment by Jannchie** [comment]
刚发现其实存在一个名为 `swapDurationMS` 的 option，能够实现修改交换速度

**Comment by bilirz** [comment]
好的好的！
