### ISSUE TITLE
如何调整每个数据的间距

### ISSUE THREAD

**Issue by ZongZihao** [Jannchie/anichart.js#18]
有比较多数据时候, 多条数据非常密集重合在了一起, 显示效果不太好, 改如何调整

**Comment by Jannchie** [comment]
柱状图的话，应该可以指定barHeight属性来强行设置每一根柱子的高度。

**Comment by ZongZihao** [comment]
> 柱状图的话，应该可以指定barHeight属性来强行设置每一根柱子的高度。

这个项目可以渲染成柱状图么, 我对js不太熟悉

**Comment by Jannchie** [comment]
> 这个项目可以渲染成柱状图么, 我对js不太熟悉

可以查看README，有柱状图的示例链接。

曲线图的话，目前确实会有重合问题，之后会尝试优化。

**Comment by Jannchie** [comment]
现在已经能够进行碰撞检测，自动弹开标签了。

**Comment by ZongZihao** [comment]
> 现在已经能够进行碰撞检测，自动弹开标签了。

好的 感觉大佬
