### ISSUE TITLE
柱状动态图时，右下角“2020-01-01”这个时间会一直晃动 看起来非常吃力

### ISSUE THREAD

**Issue by luojoe** [Jannchie/anichart.js#19]
我在这里地址https://jannchie.github.io/anichart.io/zh/edit  试用的时候发现 这个时间会左右晃动
![image](https://user-images.githubusercontent.com/14012817/100515174-fe953e00-31b4-11eb-88d8-0dcc7a043ee8.png)
我本地也是这样，但是我发现up主在B站的视频，右下角的时间很稳定。
仔细看原因是当后面的时间 为0 和 1的时候宽度不一样 ，导致一直在改变位置
我试着改了几个属性也没改好，请教一下是改哪个属性？

**Comment by Jannchie** [comment]
原因在于默认的字体不是等宽的。
你需要切换一下字体，默认是Sarasa Mono SC，如果你在系统中安装了这个字体则表现正常。
你也可以切换成任何一种等宽字体。但是字体目前似乎没有做成一个配置项暴露出来，你可能需要查找并修改源代码中指定字体的部分。

**Comment by luojoe** [comment]
下载安装字体之后 果然就好了。 🐂🍺
