### ISSUE TITLE
使用出现报错 - Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by Rabbitzzc** [Jannchie/anichart.js#2]
报错信息：
![image](https://user-images.githubusercontent.com/26913511/97189728-e01bdb80-17df-11eb-9889-feed835756fa.png)

demo：https://codesandbox.io/s/githubtrends-svc3d?file=/src/App.vue

**Comment by Jannchie** [comment]
导致这个问题的原因是，没有meta data的csv文件。我已经修复了这个问题，现在没有这个文件也能正常使用了。
另外在目前的版本中，csv中header的name需要改成id。
另外您提供的项目中，csv文件的路径不正确。本项目路径不由webpack接管，你需要将数据csv文件移动到public文件夹中才能按照相对路径正常访问到。

**Comment by Rabbitzzc** [comment]
> 导致这个问题的原因是，没有meta data的csv文件。我已经修复了这个问题，现在没有这个文件也能正常使用了。
> 另外在目前的版本中，csv中header的name需要改成id。
> 另外您提供的项目中，csv文件的路径不正确。本项目路径不由webpack接管，你需要将数据csv文件移动到public文件夹中才能按照相对路径正常访问到。

get！感谢
