### ISSUE TITLE
柱状动态图时，当背景为图片时，用node 导出图片时，所有图片都是黑的，浏览器模式是正常的

### ISSUE THREAD

**Issue by luojoe** [Jannchie/anichart.js#20]
1.柱状动态图时，当背景为图片时，用node 运行该项目,导出图片时，所有图片都是没有内容的；同样的代码，浏览器模式却是正常显示

2.柱状动态图时，当背景为纯颜色时，用node运行该项目 导出图片时，为正常

这2种情况下，test-meta的中的image图片都是可以正常加载的

PS:node运行该项目 的命令是 node --experimental-wasm-threads --experimental-wasm-bulk-memory ./test/fans-month.js

![image](https://user-images.githubusercontent.com/14012817/100549133-1ef3f400-32ac-11eb-951b-e90bc73b7472.png)

![image](https://user-images.githubusercontent.com/14012817/100549181-506cbf80-32ac-11eb-89ba-d6c73ec137d2.png)

![image](https://user-images.githubusercontent.com/14012817/100549316-3bdcf700-32ad-11eb-89e2-2fcf7a79bd80.png)

**Comment by Jannchie** [comment]
你的操作有很多槽点。首先你不能每次画背景都new一个image对象，其次你修改src之后你需要等待它载入才能绘图，因为图片是异步加载的。最后，如果想用图片作为背景，你应该直接使用ctx.drawImage而不是添加一个filter的方式曲线救国。

**Comment by luojoe** [comment]
好的，感谢大佬。我试试
