### ISSUE TITLE
TypeError: Cannot read property 'max' of undefined

### ISSUE THREAD

**Issue by littlechameleon** [Jannchie/anichart.js#23]
您好，我是这样引入anichart的，
```
<script lang="ts">
import { onMounted } from "vue";
import * as anichart from "anichart";
export default {
  setup() {
    onMounted( async () => {
      const chart = new anichart.Bar();
      await (chart as any).loadCsv("../../data/test-meta.csv");
      (chart as any).initCanvas();
      (chart as any).readyToDraw();
      console.log(chart);
      (chart as any).play()
    });
  }
}
</script>
```
但是浏览器报错如下图，

![image](https://user-images.githubusercontent.com/22498631/100912921-0f72e600-350c-11eb-8dc6-9cb103dd9c2c.png)

具体报错代码为

![image](https://user-images.githubusercontent.com/22498631/100913351-a17aee80-350c-11eb-9e00-2da8fe980807.png)

请问这个可能是什么原因呢

**Comment by Jannchie** [comment]
```js
await (chart as any).loadCsv("../../data/test-meta.csv");
```
我没有在本地调试你的代码，但大致看下可能是这个问题：
loadCsv应该载入的是数据文件，也就是test-data.csv之类的，有date和value列的文件。
test-meta.csv用于存放不会变化的数据。
可能是由于找不到任何时间序列数据，导致报了这个错误。

**Comment by zhaoli703098596** [comment]
把loadCsv("../../data/test-meta.csv")变成loadCsv(require("../../data/test-meta.csv"))就可以了
