### ISSUE TITLE
示例中视频中的数据有2处问题

### ISSUE THREAD

**Issue by luojoe** [Jannchie/anichart.js#3]
每天刷新一遍看看有没有更新，期待视频下载功能的接口开放(看到代码已经有了，但无奈js代码不太看得懂)
运行之后有两个问题(如图)
![image](https://user-images.githubusercontent.com/14012817/97274993-55cf8800-1870-11eb-8e8f-9846f1e43e7b.png)
修改方式(如图，不知道对不对)
![image](https://user-images.githubusercontent.com/14012817/97275162-8ca59e00-1870-11eb-9802-a15a4c4bf58d.png)
改完之后的结果(如图)
![image](https://user-images.githubusercontent.com/14012817/97275259-aba43000-1870-11eb-9e25-e89382d3b1c0.png)
这个月增加的粉丝和后面的总粉丝差不多， 这个业务逻辑有点不太理解

**Comment by bunnyxt** [comment]
关于`NaN`粉的问题，这里`data.total`指的是该用户某时刻的总粉丝数，之所以这里是`NaN`是因为`test-data.csv`数据没有给全，你可以手动给`test-data.csv`加上一列`total`，表示总粉丝数，再运行即可正确显示

我使用以下`python`脚本，假设总粉丝数等于当前月粉丝数*100，基于`test-data.csv`创建`test-data_2.csv`

```python
f1 = open('test-data.csv', 'r')
f2 = open('test-data_2.csv', 'w')

f2.write(f1.readline().strip('\n') + ',total\n')

for line in f1.readlines():
    num = int(list(line.rstrip('\n').split(','))[-1][1:-1])
    f2.write('%s,%d\n' % (line[:-1], num*100))

f1.close()
f2.close()
```

`test-data_2.csv`文件（部分）如下所示

```
mid,name,date,value,total
"489412051","哔哩哔哩晚会","2020-01-01","1220794",122079400
"326499679","哔哩哔哩漫画","2020-01-01","1213116",121311600
"436473455","冯提莫","2020-01-01","1054497",105449700
"19577966","李子柒","2020-01-01","954139",95413900
"456664753","央视新闻","2020-01-01","747564",74756400
```

再在`fans-month.js`中修改读入数据文件为`test-data_2.csv`，即可正常显示

```js
// let d = path.join(__dirname, "./data/test-data.csv");
let d = path.join(__dirname, "./data/test-data_2.csv");
let m = path.join(__dirname, "./data/test-meta.csv");
if (typeof window != "undefined") {
  // d = require("./data/test-data.csv");
  d = require("./data/test-data_2.csv");
  m = require("./data/test-meta.csv");
}
```

<img width="1375" alt="QQ20201027-170217@2x" src="https://user-images.githubusercontent.com/32478279/97279634-32a7d700-1876-11eb-99f3-c22202a8b710.png">

**Comment by luojoe** [comment]
csv数据不动，value就当总粉丝数，那通过计算可以得到每日增加的粉丝数，视频界面中改成+xxx粉丝/日， 这样是不是作者原本想表达的意思，也有业务意义===》前面表示每天增加的，后面表示总的

**Comment by luojoe** [comment]
你有使用他内置的导出mp4的方法吗

**Comment by bunnyxt** [comment]
> 恩 这样确实可以，和见齐自己的视频有点像https://www.bilibili.com/video/BV1ey4y1B7A5
> 你有用过他的导出mp4的方法导出视频吗

并没有，简单看了下，暂时还没有搞清楚导出视频的逻辑_8(:3 」∠ )_...

**Comment by Jannchie** [comment]
导出视频只需要在配置中加入把output设置为true。如果你使用浏览器，则会在视频生成完毕后自动下载文件。如果使用node应该可以下载到目录中。但是目前内置的导出有点慢慢的，在我这里每秒大概只能导出2帧视频。建议生成png序列再调用本地ffmpeg。

**Comment by SunlightLH** [comment]
直接通过标签引入的方式不能使用啊，报错a.loadCsv is not a function

**Comment by SunlightLH** [comment]
直接通过src引用的方式只引入文件，无法使用
<script src="https://cdn.jsdelivr.net/npm/anichart@1.0.6/dist/anichart.min.js"></script>
var d = undefined, m = undefined;
    $.ajax({
      type: "GET",
      url: "./data.csv",
      dataType: "text",
      success: function (data) {
        d = data;
      },
      error: function (request, status, error) {
        alert(request.responseText);
      }
    });
    let a = new anichart.Bar();
    a.LoadCsv(d);
    a.initCanvas();
    a.readyToDraw();
    a.play();

**Comment by Jannchie** [comment]
> 直接通过src引用的方式只引入文件，无法使用
> 
> ```
> <script src="https://cdn.jsdelivr.net/npm/anichart@1.0.6/dist/anichart.min.js"></script>
> ```
> 
> ```js
> var d = undefined, m = undefined;
>     $.ajax({
>       type: "GET",
>       url: "./data.csv",
>       dataType: "text",
>       success: function (data) {
>         d = data;
>       },
>       error: function (request, status, error) {
>         alert(request.responseText);
>       }
>     });
>     let a = new anichart.Bar();
>     a.LoadCsv(d);
>     a.initCanvas();
>     a.readyToDraw();
>     a.play();
> ```

你使用了Readme中旧版本的文件。现在我已经更新了Readme。
你可以将script中的版本信息去掉再试一次。

**Comment by luojoe** [comment]
> 直接通过src引用的方式只引入文件，无法使用
> 
> ```
> <script src="https://cdn.jsdelivr.net/npm/anichart@1.0.6/dist/anichart.min.js"></script>
> ```
> 
> ```js
> var d = undefined, m = undefined;
>     $.ajax({
>       type: "GET",
>       url: "./data.csv",
>       dataType: "text",
>       success: function (data) {
>         d = data;
>       },
>       error: function (request, status, error) {
>         alert(request.responseText);
>       }
>     });
>     let a = new anichart.Bar();
>     a.LoadCsv(d);
>     a.initCanvas();
>     a.readyToDraw();
>     a.play();
> ```
![image](https://user-images.githubusercontent.com/14012817/97404677-6f84d400-1931-11eb-9f27-2cfbe5869939.png)
参考这个图， 试一下

**Comment by luojoe** [comment]
> 导出视频只需要在配置中把output设置为true。如果你使用浏览器，则会在视频生成完毕后自动下载文件。如果使用node应该可以下载到目录中。但是目前内置的导出有点慢慢的，在我这里每秒大概只能导出2帧视频。建议生成png序列再调用本地ffmpeg。

感谢，已经可以导出来了
需要的可以参考图中的改4个地方(有3个可能是bug 😂)
![image](https://user-images.githubusercontent.com/14012817/97530437-17aba300-19ed-11eb-8b4e-4454c0b20671.png)
需要注意是用浏览器打开之后，会自动生成视频，但是速度略慢（可能4-5分钟，而好像还不能把界面放在后台 ）
