### ISSUE TITLE
呃……请问我为什么连例子都跑不起来

### ISSUE THREAD

**Issue by oOTnTOo** [Jannchie/anichart.js#34]
呃……请问我为什么连例子都跑不起来……Console报下列错误……
Fetch API cannot load file:///H:/WWW/biliob-analytics/test.csv. URL scheme must be "http" or "https" for CORS request.

**Comment by Jannchie** [comment]
你可以试试[在线示例](https://codesandbox.io/s/dreamy-microservice-e8em0?fontsize=14&hidenavigation=1&theme=dark&view=preview)

**Comment by JiaTion** [comment]
> 你可以试试[在线示例](https://codesandbox.io/s/dreamy-microservice-e8em0?fontsize=14&hidenavigation=1&theme=dark&view=preview)

大佬可以更新下[在线示例](https://codesandbox.io/s/dreamy-microservice-e8em0?fontsize=14&hidenavigation=1&theme=dark&view=preview) 到最新版吗

**Comment by JiaTion** [comment]
> > 你可以试试[在线示例](https://codesandbox.io/s/dreamy-microservice-e8em0?fontsize=14&hidenavigation=1&theme=dark&view=preview)
> 
> 大佬可以更新下[在线示例](https://codesandbox.io/s/dreamy-microservice-e8em0?fontsize=14&hidenavigation=1&theme=dark&view=preview) 到最新版吗

麻烦大佬了

**Comment by Couruo** [comment]
构建一个服务器就可以了
