### ISSUE TITLE
正常运行一会儿后出现报错The radius provided (-0.68439) is negative.

### ISSUE THREAD

**Issue by nanwy** [Jannchie/anichart.js#4]
![error2](https://user-images.githubusercontent.com/62697454/97827110-4b910c00-1cfe-11eb-804d-bcf832cda27c.png)
是数据的问题吗

**Comment by Jannchie** [comment]
给一段数据源嘛

**Comment by Jannchie** [comment]
目前似乎数据范围超出预置范围则会报错。
目前，预置范围是0到最大值，如果为负可能会报错。
我稍候会再排查一下。

**Comment by nanwy** [comment]
数据来源：https://ourworldindata.org/coronavirus-source-data
刚刚搜索了一下，确实有负数，修改后运行正常，还有如果数据如果有的日期没有数据，会导致数据日期不匹配？比如中国是从12月31日每一天都有数据，秘鲁是从3月22日才有，运行时会把秘鲁3月22日的数据和12月31日的数据一起展示，是需要把之前的日期数据补全吗

**Comment by Jannchie** [comment]
需要补全。至少需要提供一个开始的日期用于插值。
