### ISSUE TITLE
用node运行时，无法生成图片

### ISSUE THREAD

**Issue by luojoe** [Jannchie/anichart.js#5]
按照默认视频的导出方式，现在1秒钟大概导出1帧，速度有点慢。根据up主的提示，通过node运行生成图片后手动合成视频，但现在运行之后，没有生成序列图片，不知道是不是后面还有什么过程？还有如何设置输出图片的地址？
![image](https://user-images.githubusercontent.com/14012817/98096915-416e3980-1ec7-11eb-91f1-8bc72678ec9b.png)

**Comment by Jannchie** [comment]
我刚刚进行了一些修复，请下载最新的版本重新尝试一次。

**Comment by luojoe** [comment]
好的 已运行 这个错误是因为本地没有ffmpeg吗？
![image](https://user-images.githubusercontent.com/14012817/98220470-4d223480-1f89-11eb-8527-192c5d36149a.png)

**Comment by luojoe** [comment]
本地速度是真的快  300帧，1秒就完成。给力~~

**Comment by Jannchie** [comment]
well，这触发了一个新的BUG，我刚刚已经修复。
使用内置的ffmpeg不需要自行安装ffmepeg，但是无法应用cpu加速，速度比较慢。

**Comment by luojoe** [comment]
要不这几个this也加一下？不然老报错
![image](https://user-images.githubusercontent.com/14012817/98238501-6931d000-1fa1-11eb-83e7-0a09070ef7fb.png)

**Comment by Jannchie** [comment]
> 要不这几个this也加一下？不然老报错

现在已经修复了，感谢支持。
