### ISSUE TITLE
数据中value的值有0时，生成的视频中数据和时间会有问题

### ISSUE THREAD

**Issue by luojoe** [Jannchie/anichart.js#6]
如图，1，2，3号都是0，但是视频中1月2号，已经是+36万。
![image](https://user-images.githubusercontent.com/14012817/98241969-aa78ae80-1fa6-11eb-95bc-415344741f33.png)
但是同样的数据，把keyFrameDeltaTime 由 * 0.5 改成 *1  就没这个问题。昨天找了一晚上 没找到原因，那一段计算的js看不太懂
![image](https://user-images.githubusercontent.com/14012817/98242191-08a59180-1fa7-11eb-8031-e6e18e9ec340.png)

**Comment by Jannchie** [comment]
已经确认了问题，并予以修复。
修复目前没有合并到新版本，将在下次版本更新时合并。

**Comment by luojoe** [comment]
> 已经确认了问题，并予以修复。
> 修复目前没有合并到新版本，将在下次版本更新时合并。

感觉作者对项目一直默默的付出

**Comment by luojoe** [comment]
对了 为啥这次改版这么大 ，之前是柱状图，现在变成线条了。  未来是要往哪个方向改版

**Comment by Jannchie** [comment]
未来会兼容多种图表的配置

**Comment by luojoe** [comment]
改成ts了，现在还能跑之前的柱状图吗

**Comment by Jannchie** [comment]
能，[在这里](https://jannchie.github.io/anichart.io/en/demo-list)可以看到相关的示例

**Comment by luojoe** [comment]
get 期待
