### ISSUE TITLE
你好导入数据只能通过excel吗？

### ISSUE THREAD

**Issue by siwenyu0210** [Jannchie/anichart.js#75]
示例中导入数据是通过anichart.recourse.loadData("path/to/data.csv", "data")方法导入的，

**Comment by siwenyu0210** [comment]
能否把后端返回的数据导入进去

**Comment by Jannchie** [comment]
抱歉，目前还没有支持 json 导入。接下来会进行相关的开发工作。

**Comment by siwenyu0210** [comment]
你好，我通过blob解决了导入json数据的问题，但是柱状图显示有问题，请问是什么原因导致的
![image](https://user-images.githubusercontent.com/28780844/120168700-c0470d00-c231-11eb-8dc5-238274b4c84d.png)

**Comment by siwenyu0210** [comment]
你好，柱状图显示的时候有这样的问题（显示为空白），请问是什么原因




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月31日(星期一) 下午4:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Jannchie/anichart.js] 你好导入数据只能通过excel吗？ (#75)





 
抱歉，目前还没有支持 json 导入。接下来会进行相关的开发工作。

**Comment by Jannchie** [comment]
默认的颜色序列中包含白色。
通过下列方法应该可以修改默认颜色序列

``` js
import { colorPicker } from "anichart"
colorPicker.colorScheme = ["#AAA", "#BBB"]
```

**Comment by siwenyu0210** [comment]
感谢耐心解答，请问可以在演示的过程中暂停吗？

**Comment by Jannchie** [comment]
理论上是可以的，但是我可能没有提供相关接口。
你试试反复调用 stage.play() 方法能否暂停

**Comment by Jannchie** [comment]
长时间没有新的回复，我已关闭这个 Issue，如果还有疑问可以继续留言。
