### ISSUE TITLE
stage.options 的配置要怎样才生效

### ISSUE THREAD

**Issue by lanjinglingiii** [Jannchie/anichart.js#77]
stage.options 的配置不生效吗，我配置如下
stage.options.fps = 30;
stage.options.sec = 120;
然后动画不到15秒就结束了，另外还有导出视频也差不多，设置的60秒，动画过了15秒左右就不动了，但是视频从15~60的画面一直不变。我的时间格式是 yyyy-mm-dd HH:ii，不知道是不是这里的问题，示例代码其他的没改，就是改了文件的内容

**Comment by Jannchie** [comment]
请问使用的是哪个示例代码？在线 Demo 中指定了图表动画的开始和结束时间，比如：

``` js
{
  aniTime: [4, 10] // 第 4 秒开始，第 10 秒结束
}
```

如果去掉这一条配置，则会根据 stage 的 sec 自动设定时间。

在 Demo 中，因为有片头的存在，需要空出片头的时间，所以设定了 aniTime。

不知道能不能解决你的问题。

**Comment by Jannchie** [comment]
长时间没有新的回复，我已关闭这个 Issue，如果还有疑问可以继续留言。

**Comment by lanjinglingiii** [comment]
好的，我还以为那个`aniTime: [4, 10]` 是日期格式之类的东西，因为上下文刚好有一个 `dateFormat`，感谢解惑，目前问题已解决。（这些天没注意邮箱提醒回复晚了不好意思）
