### ISSUE TITLE
导出的mp4视频无法打开。

### ISSUE THREAD

**Issue by kklay** [Jannchie/anichart.js#80]
使用的是静态资源引入的2.1.1版本。设置stage.output = true; 浏览器生成的mp4文件大小没问题，但是打开是空白的。

**Comment by Couruo** [comment]
![image](https://user-images.githubusercontent.com/87072761/124752833-ed868980-df5a-11eb-85b2-4c2423f8aecb.png)
为什么我连npm run serve 都不行

**Comment by Jannchie** [comment]
> 使用的是静态资源引入的2.1.1版本。设置stage.output = true; 浏览器生成的mp4文件大小没问题，但是打开是空白的。

不好意思，未能及时回复。
我更新了代码，你可以在 [https://codesandbox.io/s/aged-snowflake-9g8vs?file=/main.js:80-82](这里) 尝试此项目是否能够导出视频。

我发现在 codesandbox 沙箱下，无法直接下载文件。在 codesandbox 中，你可以尝试在窗口打开网页实现下载。或者直接访问[https://9g8vs.csb.app/](这里)。

我这边测试没有问题。如果在这个网页下无法下载，请切换浏览器（使用 chrome 或者火狐）进行尝试。

**Comment by kklay** [comment]
https://9g8vs.csb.app/ 此地址用chrome 浏览器 依然是能生成mp4文件。文件依然无法打开正常播放。
浏览器版本
 91.0.4472.124 (正式版本) （64 位）
你导出的是否是否能正常播放呢？

**Comment by Jannchie** [comment]
> https://9g8vs.csb.app/ 此地址用chrome 浏览器 依然是能生成mp4文件。文件依然无法打开正常播放。
> 浏览器版本
>  91.0.4472.124 (正式版本) （64 位）
> 你导出的是否是否能正常播放呢？

这就很奇怪了，我这边是可以播放的。请告诉我你使用的视频播放器，也许是播放器不兼容输出的格式？

**Comment by kklay** [comment]
嗯，换了播放器确实可以打开了。应该是格式的兼容问题。谢谢回复。
