### ISSUE TITLE
run serve时出现错误

### ISSUE THREAD

**Issue by Couruo** [Jannchie/anichart.js#81]
使用命令
`npm run serve`
然后出现的是这种错误，请问是哪里出错了？
![image](https://user-images.githubusercontent.com/87072761/124752694-c29c3580-df5a-11eb-9b35-8f19c7aa320c.png)

**Comment by Jannchie** [comment]
很抱歉未能及时回复。

你在尝试本地编译并运行该项目。一般来说，这是面向“开发”，而不是“使用”的操作。

如果这真的是你想要做的，根据错误提示，没有找到相应的包，请先确认是否运行了`npm install`？

开发时，我使用的是 yarn。如果在 npm 环境中无法 build 成功，请尝试使用 yarn。

**Comment by Couruo** [comment]
谢谢。我不是特别懂，运行您的demo，会提示错误，文件必须在服务器上跑吗？
![image](https://user-images.githubusercontent.com/87072761/126034130-25cfa360-e57b-4c16-b088-732bae1e8db9.png)

**Comment by Jannchie** [comment]
> 谢谢。我不是特别懂，运行您的demo，会提示错误，文件必须在服务器上跑吗？

@Couruo 直接在 html 文件中运行，会遇到跨域错误。这是为了保证浏览器安全性。

推荐两种解决方案：

- 在本地搭建 http 服务器，并把 csv 文件放在服务器上。
- 使用这个[在线模板项目](https://codesandbox.io/s/anichart-2x-m3xbz?fontsize=14&hidenavigation=1&theme=dark)，进行制作。

**Comment by Couruo** [comment]
好的，已经构建服务器解决了，感谢您的回答。

**Comment by Couruo** [comment]
您的2xdemo似乎出了点问题，加载不出页面
![image](https://user-images.githubusercontent.com/87072761/126035080-aaebaf22-4c11-4172-8d99-9e88404ef985.png)

**Comment by Jannchie** [comment]
我这边并无问题，你看下 console 里有没有什么报错，或是什么文件下载失败？

**Comment by Couruo** [comment]
console这样显示的
![image](https://user-images.githubusercontent.com/87072761/126035290-af7371c1-2fe8-4cf8-b27d-d75ad798c488.png)

**Comment by Couruo** [comment]
firefox似乎更详细
![image](https://user-images.githubusercontent.com/87072761/126035308-5f31ff1a-4ce7-4f0c-a9b7-6e05f3d44c0c.png)

**Comment by Jannchie** [comment]
这有点奇怪。我觉得可能的一个原因是请求了墙外的资源，请试图翻墙重试。或者删除掉一些模板中依赖墙外链接的代码。
比如 main.js 中的：
```
ani.recourse.loadJSON(
  `https://raw.githubusercontent.com/Jannchie/geoJson-map-data/main/world.json`,
  "map"
);
```

**Comment by Jannchie** [comment]
由于长期没有新的回复，我关掉了这个 issue。如果需要更多的帮助，可以重新开一个。
