### ISSUE TITLE
有详细的api配置文档？示例数据有一部分配置数据，不是很明白。

### ISSUE THREAD

**Issue by Gardennias** [Jannchie/anichart.js#83]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Jannchie** [comment]
非常抱歉，目前没有API配置文档，并且因为个人精力有限，短期内无法提供完整的API或者配置项手册。
暂时，你可以尝试使用 TypeScript 编程，TypeScript 中能够进行代码提示，起到一定类似文档的作用。
或者你可以阅读 [.d.ts 文件](https://github.com/Jannchie/anichart.js/blob/master/typings/core/chart/BarChart.d.ts)。
这些文件中有配置项的全部定义。

**Comment by Jannchie** [comment]
Sorry for the wait, but I am working on a new version of the documentation and have completed the section on chart configuration items. The new documentation is now available at https://anichart.vercel.app/.
