### ISSUE TITLE
导出视频又报错了

### ISSUE THREAD

**Issue by kklay** [Jannchie/anichart.js#84]
之前提了一个导出视频报错的issues，后面可以正常导出了，现在又报错了。可用那个issues发的沙箱地址重现，直接打开就是报错。
报错信息:SharedArrayBuffer is not defined

**Comment by Jannchie** [comment]
这似乎是浏览器的版本更新导致的。我正在跟进。

**Comment by kklay** [comment]
嗯嗯，我用的chrome，92版本后貌似不支持SharedArrayBuffer了。解决后麻烦回复一下哈

**Comment by kklay** [comment]
昨天运行是正常的，今天csv文件数据一多，运行时间变成了1970-01-01开始了。。。没有按照csv文件里面的日期来运行。

**Comment by Jannchie** [comment]
> 昨天运行是正常的，今天csv文件数据一多，运行时间变成了1970-01-01开始了。。。没有按照csv文件里面的日期来运行。

能看一下你的数据嘛？有可能是有些日期未能识别。

**Comment by kklay** [comment]
有空行，把空行去掉就正常了

**Comment by Jannchie** [comment]
在线示例中直接导出视频这一功能随着浏览器安全策略的改变已经不再可能实现。

我制作了一个[项目模板](https://github.com/Jannchie/anichart-template)。通过这个项目可以快速在本地构建环境。

**Comment by kklay** [comment]
好的，谢谢
