### ISSUE TITLE
[Need Help] React函数式组件下如何使用anichart？

### ISSUE THREAD

**Issue by tyn1998** [Jannchie/anichart.js#86]
Jannchie你好，请问是否有**React中使用anichart的成功案例**？我按照[渲染条形图](https://anichart-doc.netlify.app/zh/guide/chart.html#%E5%87%86%E5%A4%87%E6%95%B0%E6%8D%AE)中的方法进行尝试，得到getTime of  undefined错误：
![2021-09-04_14-46](https://user-images.githubusercontent.com/32434520/132097174-460c521c-6879-4332-a906-4dc0c76b4a0c.png)
这个错误是每计算一帧就打印一次，因此电脑的风扇马上就转了起来，还会造成电脑的卡顿。

我能确定csv文件中的数据已经在recourse中，因为我能在控制台打印出来。

研究了大半天源码，还是力不从心，故来提issue求助。

PS：我还克隆了本仓库，使用`npm run serve`跑了test，一切正常。

**Comment by Jannchie** [comment]
已经了解，我稍后会制作一个使用react的示例。

**Comment by tyn1998** [comment]
谢谢！

**Comment by Jannchie** [comment]
我使用了 react hook 做了一个[demo](https://codesandbox.io/s/tender-gates-xyi9j?file=/src/App.js&resolutionWidth=1920&resolutionHeight=1080)，看上去是可以正常运行的。我不是 react 工程师，所以不确定这是不是所谓的函数式组件。

我不知道你使用的数据是什么样的，出现getTime未定义的问题，很可能是没有成功解析时间数据导致的。也许数据中存在意料之外的空行，或者使用了无法被解析的时间格式。

**Comment by tyn1998** [comment]
不胜感激！数据用的是anichart仓库里的测试数据，也许是我使用不当。我去学习一下Jannchie给的demo，回头再回复～

**Comment by tyn1998** [comment]
经过尝试，我发现：
`const barChart = new anichart.BarChart();`不可以；
`const barChart = new anichart.BarChart({});`可以；
`const barChart = new anichart.BarChart({dataName: "data"});`可以。

经过实验，就算不传入options，打印出来的this.dataName就是默认的“data”，可是这样子就是不成功。传入空的`{}`或显式指名`dataName`就能成功。

**Comment by Jannchie** [comment]
我在v2.4.3修复了这个问题。

**Comment by tyn1998** [comment]
赞～
