### ISSUE TITLE
一处Object.assign(old, new)的参数位置反了～

### ISSUE THREAD

**Issue by tyn1998** [Jannchie/anichart.js#87]
在`src/core/chart/BarChart.ts`的[第294行](https://github.com/Jannchie/anichart.js/blob/e6e8c38f7cca9febbc99f2a6ceab84731a3939c4/src/core/chart/BarChart.ts#L294)，是不是不小心把两个参数的位置颠倒了？

按照现在的样子，自己给出的`dateLabelOptions`不会生效。

**Comment by Jannchie** [comment]
有道理。。感谢指正
