### ISSUE TITLE
能否提供播放结束后的hook？

### ISSUE THREAD

**Issue by tyn1998** [Jannchie/anichart.js#92]
Jannchie你好~

我之前是这样实现“播放”和“重播”功能的：
- 在stage.play()后让“播放”按钮隐藏，然后紧接着一个setTimeout()，该定时器的时长为整个duration+1s
- stage播放完毕后，这个定时器也差不多走完了，定时器的内容是让“播放”按钮再次显示，达到“重播”的目的

这个定时器的方法实在不优雅，我之所以这么做是因为：目前我没有找到anichart.js在stage.play()结束后提供了相关的回调函数，从而允许用户做一些自定义的操作。

最近我还发现这个方法不仅不优雅，还很致命。这是因为：stage.play()会先加载好所有资源，但是如果资源请求的时间比较长的话，播放按钮已经消失了，但是动画还没开始走。于是定时器还是按照规定时间触发了，但是动画还没走完。造成了播放按钮提前出现的问题。

总而言之，请问Jannchie能否提供这个hook？或是有别的建议可以让我达到类似的效果？

感激不尽！

**Comment by Jannchie** [comment]
一种简单的外部解决方案是轮询。实际上，你能够从 stage 对象中获取到目前的播放进度，以及当前是否在播放（`stage.playing`）。通过定时器每隔一段时间轮询该参数，即可实现你想要的功能。

这个项目其实内置了播放控制的功能，你可以参考这里的代码实现：https://github.com/Jannchie/anichart.js/blob/master/src/core/Controller.ts

这是使用了控制器的例子，控制器会出现在页面左上角。
https://codesandbox.io/s/anichart-2x-m3xbz?fontsize=14&hidenavigation=1&theme=dark&resolutionWidth=1920&resolutionHeight=1080

**Comment by tyn1998** [comment]
谢谢Jannchie~

你给出的参考我之前都参考过了，但是轮询这个方法我没想过哈。我去试试~

非常感谢！
