### ISSUE TITLE
[BUG?] bar数比实际bar数少1

### ISSUE THREAD

**Issue by tyn1998** [Jannchie/anichart.js#93]
Jannchie你好~

最近发现了一个以前一直没留心的问题，即如题目中描述的那样，bar数比实际的bar数少1：
![image](https://user-images.githubusercontent.com/32434520/145582661-ce2aec35-ce33-46ac-a3b5-e2fa76195290.png)

这是官方sandbox中的demo，可以看到下方其他图表中都有5个数据，但是barChart只有4个。事实上，在中间变换的过程中，可以出现5个bar同时出现的情况，但是变换稳定后只有5-1=4个。data.csv中的确是5个数据。

且这和itemCount这个配置项没有关系，显示的bar永远是data.csv中实际的bar数（id数）- 1。

我自己调试源码后，发现把alpha设置成1就能让所有bar显示出来，但是最后那条被我强制显示的bar的位置显然又是不正确的：
![image](https://user-images.githubusercontent.com/32434520/145583221-e62bf061-d6e3-49d7-baff-2072af3f221b.png)

类似的，当data.csv中只有1个id的数据时，barChart将不会显示任何bar（1-1=0），也就是说进度条会走，但是stage上本该出现的1条bar没有出现。请问这是设计上无法避免的，还是说这是一个bug？

**Comment by Jannchie** [comment]
这应该是一个 bug。我之后会详细看看。

**Comment by Jannchie** [comment]
在最新的版本里，我已经修复了这个问题。

**Comment by tyn1998** [comment]
谢谢！太棒了~
