### ISSUE TITLE
新手咨询几个问题

### ISSUE THREAD

**Issue by niu541412** [Jannchie/anichart.js#94]
由于不是程序员，对js开发比较小白，但是很想用见齐大大的模板做折线图视频。
摸索了两天在线的模板，还是有几个问题找不到答案，希望可以解答。

1.  B站上您的折线图视频，数据随着时间，横轴的跨度范围是不变的，也就是在前面的数据会移出屏幕。但是默认的折线图代码和codesandbox上的例子，时间跨度会越来越大，也就是起始时间点一直在屏幕内，不知道怎么调。
2. 如何将折线图的时间轴放在折线下面？如何把纵轴对应的grid画出来？
3. 如何自定义折线的颜色，我照着以前的一个[issue](https://github.com/Jannchie/anichart.js/issues/28)试了，好像不行。看了下代码，似乎1.x版本和现在的api有了很大变化。
4. 如果比较简单的话，还想请教您如何自定义折线头的label，比如变化的数字，文字位置等。

**Comment by Jannchie** [comment]
不好意思，现在才看到消息。。

1. 折线图的跨度可以不变，但是目前我似乎没有编写出可供愉快调用的接口，我会尽快追加。
2. 时间轴位置、坐标系的配置也是一样，目前还不能自定义。
3. 自定义颜色，现在需要通过内置的 colorPicker： `ani.colorPicker.setColor(key, colorHex);`
4. 这些自定义都需要一些编程知识，并且要理解源代码。很抱歉难以解释。

对于没有编程经验的人来说，你或许可以使用百度推出的 ECharts 进行绘图，应该稍加修改就能制作出动态折线图等图表。
这个项目并不是非常成熟，由于我最近也没有在制作可视化视频（特别是折线图可视化），更新也会非常慢。
学业繁重，希望能够理解。

**Comment by niu541412** [comment]
感谢您抽空解答。
